# ---------------------------------------------------------------------------
# _sync.py
# Created on: 2011-06-13 14:41:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

print "# Syncing mobile map data"

# Set the necessary product code
#import arceditor
import arcinfo

# Import arcpy module
import arcpy

import sys
userLocalAppDir = sys.argv[1]

# Local variables:
Murrelets__sync__mxd = "C:\\KIMU\\Murrelets (sync).mxd"
MobileCache = userLocalAppDir + "\\ESRI\\ArcGIS Mobile\\P_murrelet\\MobileCache"

print "# Master Map:",Murrelets__sync__mxd
print "# Mobile Cache:",MobileCache

# Process: Synchronize Mobile Cache
arcpy.SynchronizeMobileCache_mobile(Murrelets__sync__mxd, MobileCache, "true", "true", "370000 6460000 460000 6560000", "'Bird Groups';'GPS Points';Observations;Tracks;Transects", "")

