# ---------------------------------------------------------------------------
# _sync.py
# Created on: 2011-06-13 14:41:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

print "# Syncing mobile map data"

# Set the necessary product code
#import arceditor
import arcinfo

# Import arcpy module
import arcpy

# Local variables:
Murrelets__sync__mxd = r"C:\KIMU\Murrelets (sync).mxd"
MobileCache = r"C:\KIMU\MobileProject\Murrelets (sync)"

print "# Master Map:",Murrelets__sync__mxd
print "# Mobile Cache:",MobileCache

# Process: Synchronize Mobile Cache
arcpy.SynchronizeMobileCache_mobile(Murrelets__sync__mxd, MobileCache)

print "# Data Synced!"
